### ISSUE TITLE
Suggestion to deprecate the module

### ISSUE THREAD

**Issue by BridgeAR** [ndelangen/corejs-upgrade-webpack-plugin#7]
@ndelangen as I tried to outline in https://github.com/storybookjs/storybook/issues/7445#issuecomment-625267319 it's probably a good idea to deprecate the module.

I am willing to open a PR that e.g., indicates that in the README, if that would help.

**Comment by ndelangen** [comment]
Sure, that would certainly help!

**Comment by BridgeAR** [comment]
@ndelangen would be fine with a more "prominent" approach as in replacing the whole README or do you favor just adding a short note at the top?

**Comment by ndelangen** [comment]
Short not at the top please, since for the foreseeable future people will be using storybook v5 which uses this. And I don't want them to have to dig into the history to understand what this plugin does.
